name: Checkout Speed Test

on:
  workflow_dispatch:

jobs:
  measure-checkout:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Measure raw git checkout time
        id: raw-git
        shell: pwsh
        run: |
          Write-Host "Starting raw git checkout measurement..."
          $start_time = Get-Date

          git clone --depth=1 --no-checkout --quiet https://github.com/swiftlang/llvm-project.git
          git -C llvm-project checkout HEAD

          $end_time = Get-Date
          $duration = ($end_time - $start_time).TotalSeconds

          Write-Host "Raw git checkout completed in ${duration} seconds"
          echo "duration=$duration" >> $env:GITHUB_OUTPUT

      - name: Measure actions/checkout time
        id: actions-checkout
        shell: pwsh
        run: |
          Write-Host "Starting actions/checkout measurement..."
          $start_time = Get-Date

      - name: Perform actions/checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: swiftlang/llvm-project
          fetch-depth: 1
          show-progress: false

      - name: Calculate actions/checkout duration
        id: actions-checkout-duration
        shell: pwsh
        run: |
          $end_time = Get-Date
          $duration = ($end_time - $start_time).TotalSeconds

          Write-Host "actions/checkout completed in ${duration} seconds"
          echo "duration=$duration" >> $env:GITHUB_OUTPUT
