name: Checkout Speed Test

on:
  workflow_dispatch:

jobs:
  measure-checkout:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Measure raw git checkout time
        id: raw-git
        run: |
          echo "Starting raw git checkout measurement..."
          start_time=$(date +%s.%N)

          git clone --depth=1 --no-checkout --progress https://github.com/swiftlang/llvm-project.git
          git -C llvm-project checkout HEAD

          end_time=$(date +%s.%N)
          duration=$(echo "$end_time - $start_time" | bc)

          echo "Raw git checkout completed in ${duration} seconds"
          echo "duration=$duration" >> $GITHUB_OUTPUT

      - name: Create Raw Git Sparkline
        run: |
          duration=${{ steps.raw-git.outputs.duration }}
          scaled_duration=$(echo "$duration * 10" | bc | cut -d. -f1)
          sparkline=""

          for ((i=1; i<=$scaled_duration; i++)); do
            sparkline+="▁"
          done

          echo "Raw Git Checkout Speed Sparkline: $sparkline"
          echo "Raw Git Duration: ${duration}s"

      - name: Measure actions/checkout time
        id: actions-checkout
        run: |
          echo "Starting actions/checkout measurement..."
          start_time=$(date +%s.%N)

      - name: Perform actions/checkout
        uses: actions/checkout@v4
        with:
          repository: swiftlang/llvm-project
          fetch-depth: 1
          show-progress: false

      - name: Calculate actions/checkout duration
        id: actions-checkout-duration
        run: |
          end_time=$(date +%s.%N)
          duration=$(echo "$end_time - $start_time" | bc)

          echo "actions/checkout completed in ${duration} seconds"
          echo "duration=$duration" >> $GITHUB_OUTPUT

      - name: Create Actions Checkout Sparkline
        run: |
          duration=${{ steps.actions-checkout-duration.outputs.duration }}
          scaled_duration=$(echo "$duration * 10" | bc | cut -d. -f1)
          sparkline=""

          for ((i=1; i<=$scaled_duration; i++)); do
            sparkline+="▁"
          done

          echo "Actions Checkout Speed Sparkline: $sparkline"
          echo "Actions Checkout Duration: ${duration}s"
