name: "main"
on:
  push:
    branches:
      - main

jobs:
  create_values:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ['a', 'b', 'c']
    steps:
      - name: Print ${{ matrix.value }}
        shell: bash
        run: |
          echo "I'm value ${{ matrix.value }}"
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.value }}
          outputs: |-
            matrix_value: ${{ matrix.value }}
            other_thing: ${{ join(matrix.value, 'lol') }}
  read:
    runs-on: ubuntu-latest
    needs: [create_values]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: create_values
    outputs:
      result: "${{ steps.read.outputs.result }}"

  assert:
    runs-on: ubuntu-latest
    needs: [read]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: a
          ## This how you can reference matrix output
          actual: ${{ fromJson(needs.read.outputs.result).matrix_value.a }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: b
          ## This how you can reference matrix output
          actual: ${{ fromJson(needs.read.outputs.result).matrix_value.b }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: c
          ## This how you can reference matrix output
          actual: ${{ fromJson(needs.read.outputs.result).matrix_value.c }}

