name: "main"
on:
  push:
    branches:
      - main

jobs:
  create_values:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ['a', 'b', 'c']
    steps:
      - name: Print ${{ matrix.value }}
        shell: bash
        run: |
          echo "I'm value ${{ matrix.value }}"
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.value }}
          outputs: |-
            matrix_value: ${{ matrix.value }}
            other_thing: ${{ join(matrix.value, 'lol') }}
  read:
    runs-on: ubuntu-latest
    needs: [create_values]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: create_values
      - name: "Serialize Into Array"
        id: serialize
        run: |-
          set -eux
          DATA=$(echo '${{ toJson(steps.read.outputs.result)}}' | jq -rc 'fromjson | [.[]] | .')
          echo "result=$DATA" >> "$GITHUB_OUTPUT"
    outputs:
      result: ${{ steps.serialize.outputs.result }}

  assert_matrix:
    name: "Assert ${{ matrix.include.a }}"
    runs-on: ubuntu-latest
    needs: [read]
    strategy:
      matrix:
        include: ${{ fromJson(needs.read.outputs.result) }}
    steps:
      - name: "Dump Info"
        run: |-
          echo ${{ needs.read.outputs.result }}
          echo "fromJSON: ${{ fromJson(needs.read.outputs.result) }}"
          echo ${{ matrix.include }}
          echo "matrix fromJSON ${{ fromJson(matrix.include) }}"
      - name: "Echo"
        run: |-
          echo "stuff ${{ matrix.include }}"

