name: Reset PR Checks on Base Change

on:
  pull_request:
    types: [edited]

jobs:
  reset-checks:
    runs-on: ubuntu-latest
    if: github.event.changes.base.ref != ''  # Only run if base branch was changed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR number
        id: pr
        run: echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Reset status checks
        run: |
          # Get all check runs for the PR
          CHECK_RUNS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs")

          # Extract check run IDs
          CHECK_RUN_IDS=$(echo $CHECK_RUNS | jq '.check_runs[].id')

          # Delete each check run
          for check_id in $CHECK_RUN_IDS; do
            curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/check-runs/$check_id"
          done

          echo "All status checks have been reset"
