name: "pull request"
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  run_stuff:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Say Hi
        run: |
          echo "Hi Mom!"
      - name: Run script
        run: |
          set -o pipefail
          read -r -d '' DATA << EOM
          hi
          EOM
          parsed=$(echo $DATA | jq -cs '.')
          echo "pased output is: $parsed"
          export THING=$parsed
          echo "matrix=$parsed" >> $GITHUB_SUMMARY
