name: Rerun PR Checks on Base Change

on:
  pull_request:
    types: [edited]

permissions:
  checks: write
  pull-requests: write
  actions: write   # Needed for rerunning workflows

jobs:
  rerun-checks:
    runs-on: ubuntu-latest
    if: github.event.changes.base.ref != ''  # Only run if base branch was changed

    steps:
      - name: Rerun all workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all workflow runs for this PR
          runs=$(gh api \
            repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.pull_requests[].number == ${{ github.event.pull_request.number }}) | .id')

          # Rerun each workflow
          echo "$runs" | while read run_id; do
            echo "Rerunning workflow run $run_id"
            gh api \
              --method POST \
              repos/${{ github.repository }}/actions/runs/$run_id/rerun
          done
