name: Reset PR Checks on Base Change

on:
  pull_request:
    types: [edited]

permissions:
  checks: write
  pull-requests: write

jobs:
  reset-checks:
    runs-on: ubuntu-latest
    if: github.event.changes.base.ref != ''  # Only run if base branch was changed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR number
        id: pr
        run: echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Reset status checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub CLI to get the check runs
          checks=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs \
            --jq '.check_runs[] | select(.status != "completed") | .id')

          # Delete each check run
          if [ ! -z "$checks" ]; then
            echo "Found active checks to reset"
            echo "$checks" | while read check_id; do
              echo "Deleting check run $check_id"
              gh api \
                --method DELETE \
                repos/${{ github.repository }}/check-runs/$check_id
            done
          else
            echo "No active checks found to reset"
          fi

      - name: Retrigger pull_request event
        run: |
          # Update the PR branch to trigger a synchronize event
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/update-branch"
