name: Rerun PR Checks on Base Change

on:
  pull_request:
    types: [edited]

permissions:
  checks: write
  pull-requests: write
  actions: write   # Needed for rerunning workflows

jobs:
  rerun-checks:
    runs-on: ubuntu-latest
    if: github.event.changes.base.ref != ''  # Only run if base branch was changed

    steps:
      - name: Rerun pull_request workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest pull_request workflow run for this PR
          run_id=$(gh api \
            repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.event == "pull_request" and .head_sha == "${{ github.event.pull_request.head.sha }}") | .id' \
            | head -n1)

          if [ ! -z "$run_id" ]; then
            echo "Rerunning workflow run $run_id"
            gh api \
              --method POST \
              repos/${{ github.repository }}/actions/runs/$run_id/rerun
          else
            echo "No pull_request workflow run found to rerun"
          fi
